# Generated by Django 4.2.30 on 2026-06-28 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000)]),
        ),
    ]
