# Generated by Django 4.2.30 on 2026-06-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_alter_leavebalance_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Holiday',
                'verbose_name_plural': 'Company Holidays',
                'db_table': 'leaves_holiday',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='idx_holiday_date')],
            },
        ),
    ]
