# Generated by Django 4.2.30 on 2026-06-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_holiday'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='leaverequest',
            name='idx_leavereq_emp_status',
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee', 'status', 'leave_type'], name='idx_leavereq_emp_stat_type'),
        ),
    ]
