# Generated by Django 4.2.30 on 2026-06-28 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaves', '0004_remove_leaverequest_idx_leavereq_emp_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='review_note',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='reviewed_by',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['manager', 'status'], name='idx_leavereq_manager_status'),
        ),
    ]
