# Generated by Django 4.2.30 on 2026-06-28 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employeeprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaves', '0005_remove_leaverequest_review_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='users.employeeprofile', to_field='user'),
        ),
        migrations.CreateModel(
            name='LeaveAdjustmentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_amount', models.DecimalField(decimal_places=1, help_text='Positive for addition, negative for deduction.', max_digits=5)),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(help_text='HR Admin who made the adjustment.', on_delete=django.db.models.deletion.PROTECT, related_name='made_leave_adjustments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_adjustments', to='users.employeeprofile')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='leaves.leavetype')),
            ],
            options={
                'db_table': 'leaves_leaveadjustmentauditlog',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['employee', 'timestamp'], name='idx_leaveadj_emp_time')],
            },
        ),
    ]
