# Generated by Django 4.2.30 on 2026-06-28 16:22

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0006_alter_leavebalance_employee_leaveadjustmentauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_annual_days', models.DecimalField(decimal_places=1, help_text='Default number of days allocated annually to employees.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this policy is currently active for automatic allocation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.OneToOneField(help_text='The leave type this policy applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='leaves.leavetype')),
            ],
            options={
                'verbose_name': 'Leave Policy',
                'verbose_name_plural': 'Leave Policies',
                'db_table': 'leaves_leavepolicy',
            },
        ),
    ]
