# Generated by Django 4.2.30 on 2026-06-28 16:22

from django.db import migrations


def seed_leave_policies(apps, schema_editor):
    LeaveType = apps.get_model('leaves', 'LeaveType')
    LeavePolicy = apps.get_model('leaves', 'LeavePolicy')

    policies = [
        {'name': 'Sick Leave', 'default_days': 12.0, 'max_days': 30},
        {'name': 'Casual Leave', 'default_days': 12.0, 'max_days': 20},
        {'name': 'Paid Leave', 'default_days': 20.0, 'max_days': 40},
    ]

    for p in policies:
        leave_type, created = LeaveType.objects.get_or_create(
            name=p['name'],
            defaults={'max_days_per_year': p['max_days'], 'is_active': True}
        )
        LeavePolicy.objects.get_or_create(
            leave_type=leave_type,
            defaults={'default_annual_days': p['default_days'], 'is_active': True}
        )

def unseed_leave_policies(apps, schema_editor):
    LeaveType = apps.get_model('leaves', 'LeaveType')
    LeavePolicy = apps.get_model('leaves', 'LeavePolicy')
    names = ['Sick Leave', 'Casual Leave', 'Paid Leave']
    LeavePolicy.objects.filter(leave_type__name__in=names).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0007_leavepolicy'),
    ]

    operations = [
        migrations.RunPython(seed_leave_policies, unseed_leave_policies)
    ]

