# Generated by Django 4.2.30 on 2026-06-28 17:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0008_seed_leave_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveadjustmentauditlog',
            name='new_balance',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Balance after the adjustment.', max_digits=5),
        ),
        migrations.AddField(
            model_name='leaveadjustmentauditlog',
            name='previous_balance',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Balance before the adjustment.', max_digits=5),
        ),
    ]
