# Generated by Django 4.2.30 on 2026-06-28 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text='The job title or internal role of the employee.', max_length=100, verbose_name='job role/title')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this employee is currently active in the company.', verbose_name='active status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, help_text='The manager this employee reports to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='users.employeeprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'employee profile',
                'verbose_name_plural': 'employee profiles',
                'db_table': 'users_employeeprofile',
            },
        ),
    ]
